In [9]:
import zipfile
zip_file = zipfile.ZipFile('/openbayes/home/LGG-main.zip', 'r')
zip_file.extractall()
zip_file.close()

In [3]:
!pip install -r requirements.txt
# Run

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 735.5/735.5 MB 5.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 109.4 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 106.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 84.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 91.8 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.4
    Uninstalling numpy-1.23.4:
      Successfully uninstalled numpy-1.23.4
  Attempting uninstall: torch
    Found existing installation: torch 1.8.2+cu111
    Uninstalling torch-1.8.2+cu111:
      Successfully uninstalled torch-1.8.2+cu111
  Attempting uninstall: scipy
    Found existing installation: scipy 1.9.2
    Uninstalling scipy-1.9.2:
      Successfully uninstalled scipy-1.9.2
  Attempting uninstall: s

In [7]:
!pip install torch==2.0.1 numpy==1.21.0

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 3.6 MB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 5.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 5.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 3.8 MB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 8.6 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 5.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 4.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 MB 5.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 5.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
!python main-DEAP.py --data-path '/openbayes/input/input0' --label-type 'V' --graph-type 'gen'

/openbayes/input/input0/s01.dat
data:(40, 32, 7680) label:(40, 4)
Binary label generated!
The data and label are split: Data shape:(40, 15, 1, 32, 512) Label:(40, 15)
Data and label prepared!
data:(40, 15, 1, 32, 512) label:(40, 15)
----------------------
/openbayes/input/input0/s02.dat
data:(40, 32, 7680) label:(40, 4)
Binary label generated!
The data and label are split: Data shape:(40, 15, 1, 32, 512) Label:(40, 15)
Data and label prepared!
data:(40, 15, 1, 32, 512) label:(40, 15)
----------------------
/openbayes/input/input0/s03.dat
data:(40, 32, 7680) label:(40, 4)
Binary label generated!
The data and label are split: Data shape:(40, 15, 1, 32, 512) Label:(40, 15)
Data and label prepared!
data:(40, 15, 1, 32, 512) label:(40, 15)
----------------------
/openbayes/input/input0/s04.dat
data:(40, 32, 7680) label:(40, 4)
Binary label generated!
The data and label are split: Data shape:(40, 15, 1, 32, 512) Label:(40, 15)
Data and label prepared!
data:(40, 15, 1, 32, 512) label:(40, 15)

In [5]:
!nvidia-smi

Sat Aug 26 16:07:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:A1:00.0 Off |                  N/A |
| 30%   25C    P8    21W / 350W |      1MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
!pip install scipy

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [7]:

!pip install spicy

from scipy.io import loadmat

# 加载.mat文件
data = loadmat('/openbayes/input/input0/s03.mat')

# 打印文件内容
for key, value in data.items():
    # 过滤MATLAB的特殊项
    if not key.startswith('__'):
        print(f"{key}:\n{value}\n")


Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
labels:
[[5.33 4.67 4.97 4.45]
 [7.21 4.44 5.22 6.23]
 [7.55 2.81 5.91 6.81]
 [4.69 3.69 5.   4.19]
 [6.92 4.44 5.56 7.17]
 [6.79 1.97 4.38 7.32]
 [5.45 3.01 5.04 5.79]
 [7.14 4.33 5.74 6.35]
 [7.33 3.23 5.99 7.78]
 [4.45 5.49 5.71 5.23]
 [7.94 3.12 4.23 7.1 ]
 [6.36 3.15 3.12 6.29]
 [7.91 2.97 3.68 6.99]
 [7.29 3.86 4.4  7.29]
 [7.36 2.92 3.81 5.88]
 [7.15 4.37 4.03 7.54]
 [4.56 1.78 4.1  5.41]
 [7.1  2.13 5.04 6.32]
 [8.14 3.17 5.47 7.97]
 [6.26 3.13 4.32 5.23]
 [4.99 6.44 4.54 6.55]
 [4.94 1.   4.13 6.21]
 [3.65 2.5  3.03 5.92]
 [3.31 2.27 1.91 6.78]
 [3.45 1.41 2.9  6.87]
 [4.67 1.18 2.64 6.94]
 [6.72 3.29 4.46 6.22]
 [5.59 2.51 2.65 6.59]
 [4.47 3.85 3.08 7.14]
 [3.87 3.09 2.72 6.12]
 [4.44 4.06 4.63 5.  ]
 [5.17 4.49 5.91 6.55]
 [4.05 3.83 5.5  4.99]
 [4.72 8.12 5.85 5.33]
 [3.18 5.04 5.65 3.15]
 [5.01 5.5  4.54 3.86]
 [4.92 6.05 5.46 5.26]
 [4.53 5.68 5.65 5.49]
 [4.33 6.21 5.68 4.62]
 [5.38 4.33 5.67 5.29]]

data:
[[[

In [2]:
!git clone https://github.com/sodacode1/LGGNet_DEAP.git

fatal: destination path 'LGGNet_DEAP' already exists and is not an empty directory.


In [3]:
cd LGGNet_DEAP

/output/LGGNet_DEAP


In [6]:
!git log

commit ce888f1dc55c15a0bbad454b2403cab286f32731 (HEAD -> main, origin/main, origin/HEAD)
Author: sodacode1 <105784762+sodacode1@users.noreply.github.com>
Date:   Sun Aug 27 15:27:06 2023 +0800

    Initial commit


In [7]:
!git add .
 


In [6]:
!git config --global user.email "s1981834@163.com"
!git config --global user.name "sodacode1"


In [8]:
!git commit -m "Initial commit"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
